# Generated by Django 5.2 on 2025-11-29 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_order_completion_message_order_estimated_ready_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200)),
                ('customer_email', models.EmailField(max_length=254)),
                ('rating', models.IntegerField(choices=[(5, '⭐⭐⭐⭐⭐ Excellent'), (4, '⭐⭐⭐⭐ Very Good'), (3, '⭐⭐⭐ Good'), (2, '⭐⭐ Fair'), (1, '⭐ Poor')])),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved', models.BooleanField(default=False)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='menu.order')),
            ],
            options={
                'verbose_name_plural': 'Feedbacks',
                'ordering': ['-created_at'],
            },
        ),
    ]
