# Generated by Django 5.2 on 2025-12-03 09:38

from django.db import migrations, models


def set_existing_order_totals(apps, schema_editor):
    Order = apps.get_model('menu', 'Order')
    for order in Order.objects.all():
        order.final_amount = order.total_amount
        if order.delivery_fee is None:
            order.delivery_fee = 0
        if order.discount_amount is None:
            order.discount_amount = 0
        order.save(update_fields=['final_amount', 'delivery_fee', 'discount_amount'])


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_contactmessage_faq_galleryimage_newslettersubscriber_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_option',
            field=models.CharField(choices=[('pickup', 'Pickup at Store'), ('delivery', 'Courier Delivery'), ('dine_in', 'Dine-in Service'), ('curbside', 'Curbside')], default='pickup', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='order',
            name='discount_code',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='final_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Pay in Store'), ('card', 'Credit/Debit Card'), ('wallet', 'Mobile Wallet')], default='cash', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20),
        ),
        migrations.RunPython(set_existing_order_totals, migrations.RunPython.noop),
    ]
